=== TalibMari/EbadRepo/Data.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.xyz.com"
xmlns="http://www.xyz.com"
elementFormDefault="qualified">

    <xs:element name="note">
        <xs:complexType >
            <xs:sequence >
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"  maxOccurs="unbounded" minOccurs="1"/>
                        <xs:element name="age" type="xs:int" />
                        <xs:element name="date" type="xs:date" />
                        <xs:element name="time" type="xs:time" />
                        <xs:element name="DateAndTime" type="xs:dateTime" />
                        <xs:element name="Decimal" type="xs:decimal" />
                    </xs:sequence>
                </xs:complexType>
                </xs:element>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TalibMari/EbadRepo/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<note xmlns="http://www.xyz.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.xyz.com Data.xsd">
    <student>
        First Name:
        <name>Usama</name>
        <age>22</age>
        <date>2022-05-12</date>
        <time>05:59:34</time>
        <DateAndTime>2022-05-12T05:59:34</DateAndTime>
        <Decimal>10.0</Decimal>
    </student>


    <student>
        First Name:
        <name>Rex</name>
        <age>22</age>
        <date>2022-05-12</date>
        <time>05:59:34</time>
        <DateAndTime>2022-05-12T05:59:34</DateAndTime>
        <Decimal>10.0</Decimal>
    </student>

    <student>
        <name>Abc</name>
        <age>22</age>
        <date>2022-05-12</date>
        <time>05:59:34</time>
        <DateAndTime>2022-05-12T05:59:34</DateAndTime>
        <Decimal>10.0</Decimal>
    </student>
</note>
